// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type In struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Out struct {
	Textout string `json:"textout"`
}
